server:
  port: 8866
  undertow:
    io-threads: 16
    worker-threads: 256
    buffer-size: 1024
    direct-buffers: true
    
spring:
 
  redis:
    database: 2
    timeout: 5000
    host: localhost
    port: 6379
    password: pass
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0 
        
  quartz:
    properties:
      driver: com.mysql.jdbc.Driver   
      URL: jdbc:mysql://localhost:3306/quartz?useUnicode=true&characterEncoding=utf8
      user: root
      password: root
      validationQuery: select 0 from dual
          
    
        